name: 'SecObserve Vulnerability Scanner'
description: 'Invokes several vunerability scanners'
author: 'MaibornWolff'

inputs:
  so_configuration:
    description: 'The YAML file with the configuration for the vulnerability scanners.'
    required: true
  so_api_token:
    description: 'API token of the user to be used for the import.'
    required: true

runs:
  using: 'docker'
  image: 'docker://docker.io/maibornwolff/secobserve-scanners:2025_09'
  entrypoint: '/entrypoints/entrypoint_vulnerability_scanner.sh'
  env:
    SO_CONFIGURATION: ${{ inputs.so_configuration }}
    SO_API_TOKEN: ${{ inputs.so_api_token }}
