name: Build and push latest images from main

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push scanners
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker//Dockerfile
          push: true
          tags: maibornwolff/secobserve-scanners:latest
      -
        name: Build and push OWASP ZAP
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker_zap//Dockerfile
          push: true
          tags: maibornwolff/secobserve-scanners-zap:latest
