name: Build and push release images from main

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'SecObserve scanners release (without the v)'
        required: true

permissions: read-all

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'v${{ github.event.inputs.release }}'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push scanners
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker//Dockerfile
          push: true
          tags: |
            maibornwolff/secobserve-scanners:${{ github.event.inputs.release }}
            maibornwolff/secobserve-scanners:latest
          build-args:
            VERSION=${{ github.event.inputs.release }}
      -
        name: Build and push OWASP ZAP
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker_zap//Dockerfile
          push: true
          tags: |
            maibornwolff/secobserve-scanners-zap:${{ github.event.inputs.release }}
            maibornwolff/secobserve-scanners-zap:latest
          build-args:
            VERSION=${{ github.event.inputs.release }}
