name: Build and push dev images

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set current date as env variable
        run: echo "CREATED=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      -
        name: Build and push scanners
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker//Dockerfile
          push: true
          tags: maibornwolff/secobserve-scanners:dev
          build-args: |
            CREATED=${{ env.CREATED }}
            REVISION=${{ github.sha }}
            VERSION=dev
      -
        name: Build and push ZAP
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker_zap//Dockerfile
          push: true
          tags: maibornwolff/secobserve-scanners-zap:dev
          build-args: |
            CREATED=${{ env.CREATED }}
            REVISION=${{ github.sha }}
            VERSION=dev
